config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'users/new'

  get 'user/new'

  root 'static_pages#home'
  get 'home' => 'static_pages#help'
  get 'static_pages/help'
  get 'help' => 'static_pages#help'
  get 'static_pages/about'
  get 'about' => 'static_pages#about'
  get 'static_pages/contact'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'introduction' => 'static_pages#introduction'
  get 'documents' => 'static_pages#documents'
  get 'utilize' => 'static_pages#utilize'
  resources :users
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
    before_save {self.email = email.downcase}
    VALID_EMAIL_REGEX = /\A[\w\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :name, presence: true, length: {maximum:50}
    validates :email, presence: true, length: {maximum:255},
                      format: {with: VALID_EMAIL_REGEX},
                      uniqueness: {case_sensitive: false}
    has_secure_password
    validates :password, length: {minimum:8}
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
  
  def introduction
  end
  
  def documents
  end
  
  def utilize
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                     :password_confirmation)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title = '')
        base_title = "International FTAs Portal Sample App"
        if page_title.empty?
            base_title
        else
            "#{page_title} | #{base_title}"
        end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # Logs in the given user.
    def log_in(user)
        session[:user_id] = user.id
    end
      # Returns the current logged-in user (if any).
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    # Returns true if the user is logged in, false otherwise.
    def logged_in?
        !current_user.nil?
    end

    # Logs out the current user.
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    
    # Returns the Gravatar for the given user.
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The FTAs International Portal Copyright by Hien Tran 2016
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "international FTAs portal", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", "#" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", "#" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title,"About") %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/documents.html.erb
<% provide(:title,"Documents") %>
<h1>Documents about WTO & FTAs</h1>
<p>Documents about WTO and FTAs</p>
<p><%= link_to 'FTA guidebook','http://www.spring.gov.sg/Resources/Documents/Guidebook_FTA_Guide_Goods.pdf' %></p>
<p><%= link_to 'FTA guidebook for SMEs', 'http://www.spring.gov.sg/Resources/Documents/Guidebook_FTA_Guide_Services_Eng.pdf'%></p>

app/views/static_pages/help.html.erb
<% provide(:title,"Help") %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron" id="landpage_bg">
  <h1>Welcome to the International FTAs Portal</h1>

  <h2>
    This is the home page for the
    International FTAs Portal
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<div class="container-fluid">
  <h1>Visit our application to</h1>
  <div class="row">
    <div class="col-sm-3 col-md-6 col-lg-4" >
      	<h2>Introduction about FTA & WTO introduction</h2>
      	<%= link_to image_tag("wtoicon.png",size: '256x256', class: "img-responsive"),introduction_path  %>
    </div>
    <div class="col-sm-3 col-md-6 col-lg-4">
      <h2>FTA documents</h2>
      <%= link_to image_tag("documents.png",size: '256x256', class:"img-responsive"), documents_path%>
    </div>
    <div class="col-sm-3 col-md-6 col-lg-4">
      <h2>How to utilize FTA to reduce cost of shipping </h2>
      <%= link_to image_tag("money.png",size: '256x256', class: "img-responsive"), utilize_path %>
    </div>
  </div>
</div>
            

app/views/static_pages/introduction.html.erb
<% provide(:title,"Introduction") %>
<h1>Introduction about WTO & FTAs</h1>
<h2>What is the WTO?</h2>
<p>The World Trade Organization (WTO) is the only global international organization dealing with the rules of trade between nations. At its heart are the WTO agreements, negotiated and signed by the bulk of the world’s trading nations and ratified in their parliaments. The goal is to help producers of goods and services, exporters, and importers conduct their business.</p>
<h2>What WTO do </h2>
<p> The WTO is run by its member governments. All major decisions are made by the membership as a whole, either by ministers (who usually meet at least once every two years) or by their ambassadors or delegates (who meet regularly in Geneva).</p>
<p>While the WTO is driven by its member states, it could not function without its Secretariat to coordinate the activities. The Secretariat employs over 600 staff, and its experts — lawyers, economists, statisticians and communications experts — assist WTO members on a daily basis to ensure, among other things, that negotiations progress smoothly, and that the rules of international trade are correctly applied and enforced.

<h4>Trade negotiations</h4>

<p>The WTO agreements cover goods, services and intellectual property. They spell out the principles of liberalization, and the permitted exceptions. They include individual countries’ commitments to lower customs tariffs and other trade barriers, and to open and keep open services markets. They set procedures for settling disputes. These agreements are not static; they are renegotiated from time to time and new agreements can be added to the package. Many are now being negotiated under the Doha Development Agenda, launched by WTO trade ministers in Doha, Qatar, in November 2001. </p>

<h4>Implementation and monitoring</h4>

<p>WTO agreements require governments to make their trade policies transparent by notifying the WTO about laws in force and measures adopted. Various WTO councils and committees seek to ensure that these requirements are being followed and that WTO agreements are being properly implemented. All WTO members must undergo periodic scrutiny of their trade policies and practices, each review containing reports by the country concerned and the WTO Secretariat.</p>

<h4>Dispute settlement</h4>

<p>The WTO’s procedure for resolving trade quarrels under the Dispute Settlement Understanding is vital for enforcing the rules and therefore for ensuring that trade flows smoothly. Countries bring disputes to the WTO if they think their rights under the agreements are being infringed. Judgements by specially appointed independent experts are based on interpretations of the agreements and individual countries’ commitments.</p>

<h4>Building trade capacity</h4>

<p>WTO agreements contain special provision for developing countries, including longer time periods to implement agreements and commitments, measures to increase their trading opportunities, and support to help them build their trade capacity, to handle disputes and to implement technical standards. The WTO organizes hundreds of technical cooperation missions to developing countries annually. It also holds numerous courses each year in Geneva for government officials. Aid for Trade aims to help developing countries develop the skills and infrastructure needed to expand their trade.</p>

<h4>Outreach</h4>

<p>The WTO maintains regular dialogue with non-governmental organizations, parliamentarians, other international organizations, the media and the general public on various aspects of the WTO and the ongoing Doha negotiations, with the aim of enhancing cooperation and increasing awareness of WTO activities.</p>

app/views/static_pages/utilize.html.erb
<% provide(:title,"Utilize WTO & FTA") %>
<h1>Utilize WTO & FTAs</h1>
<p>Utilize WTO and FTAs</p>

app/views/user/new.html.erb
<h1>Signup</h1>
<p>This will be a signup page for new user</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control'  %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>